# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4d6e5099b6eca3473079d3b05c051ef6e702927d7638b3498884cca9812a6e4d3e41e4a8f473b1d2ee6055288622ed184fe5fa4a66aecdcdcf012e3bd92feca

test:
  secret_key_base: 5c92b1786a1e968742a71825a326f426ac9998165e3f29fad8718fb3ff93a0600d184cd0188e387a436cb53bd5f9e8c4f6d222aa07d13a146e0f5c30d8ef7089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
